const LANG_KEY = 'shila_lang';

const translations: any = {
  en: {
    'timeline.bank_guarantee.received': 'Inbox',
'timeline.bank_guarantee.drafting': 'Process',
'timeline.bank_guarantee.checking': 'Checking',
'timeline.bank_guarantee.released': 'Release',
'chart.bank_guarantee.inbox': 'Inbox',
'chart.bank_guarantee.drafting': 'Process',
'chart.bank_guarantee.checking': 'Checking',
'action.bank_guarantee.start_drafting': '▶ Start Process',
'action.bank_guarantee.start_checking': '🔍 Start Checking',
    'nav.main_menu': 'Main Menu',
    'timeline.export.received': 'Inbox',
    'timeline.export.drafting': 'Checking Analyst',
    'timeline.export.checking': 'Checking Officer',
    'timeline.export.released': 'Release',
    'chart.export.inbox': 'Inbox',
    'chart.export.drafting': 'Checking Analyst',
    'chart.export.checking': 'Checking Officer',
    'action.export.start_drafting': '▶ Start Checking Analyst',
    'action.export.start_checking': '🔍 Start Checking Officer',
    'timeline.bank guarantee.received': 'Inbox',
    'timeline.bank guarantee.drafting': 'Process',
    'timeline.bank guarantee.checking': 'Checking',
    'timeline.bank guarantee.released': 'Release',
    'chart.bank guarantee.inbox': 'Inbox',
    'chart.bank guarantee.drafting': 'Process',
    'chart.bank guarantee.checking': 'Checking',
    'action.bank guarantee.start_drafting': '▶ Start Process',
    'action.bank guarantee.start_checking': '🔍 Start Checking',
    'timeline.import.received': 'Inbox',
    'timeline.import.drafting': 'Drafting',
    'timeline.import.checking': 'Checking',
    'timeline.import.released': 'Release',
    'chart.import.inbox': 'Inbox Wait',
    'chart.import.drafting': 'Drafting',
    'chart.import.checking': 'Checking',
    'action.import.start_drafting': '▶ Start Drafting',
    'action.import.start_checking': '🔍 Start Checking',
    'nav.operations': 'Operations',
    'nav.exec_dashboard': 'Executive Dashboard',
    'nav.import': 'Import',
    'nav.export': 'Export',
    'nav.bg': 'Bank Guarantee',
    'nav.dashboard': 'Dashboard',
    'nav.queue': 'L/C Queue',
    'nav.officer_release': 'Officer Release L/C',
    'nav.create': 'Create Order',
    'nav.master_data': 'Master Data',
    'nav.assignee_master': 'L/C Assignee Master',
    'nav.officer_registration': 'Officer Registration',
    'nav.sla': 'SLA Settings',
    'nav.eventlog': 'Event Log',
    'sidebar.user_role': 'Administrator',
    'topbar.reset': '↻ Reset Data',
    'page.exec_dashboard.title': 'Executive Dashboard',
    'page.exec_dashboard.breadcrumb': 'Shila Dashboard / Executive Overview',
    'page.import.title': 'Import Operations',
    'page.import.breadcrumb': 'Shila Dashboard / Import',
    'page.export.title': 'Export Operations',
    'page.export.breadcrumb': 'Shila Dashboard / Export',
    'page.bg.title': 'Bank Guarantee Operations',
    'page.bg.breadcrumb': 'Shila Dashboard / Bank Guarantee',
    'page.dashboard.title': 'Dashboard',
    'page.dashboard.breadcrumb': 'Shila Dashboard / Overview',
    'page.queue.title': 'L/C Processing Queue',
    'page.queue.breadcrumb': 'Shila Dashboard / L/C Queue',
    'page.officer_release.title': 'Officer Release L/C',
    'page.officer_release.breadcrumb': 'Shila Dashboard / Officer Release',
    'page.create.title': 'Create Order',
    'page.create.breadcrumb': 'Shila Dashboard / Create Order',
    'page.assignee_master.title': 'L/C Assignee Master',
    'page.assignee_master.breadcrumb': 'Shila Dashboard / Master Data / Assignee',
    'page.officer_registration.title': 'Officer Registration',
    'page.officer_registration.breadcrumb': 'Shila Dashboard / Master Data / Officer Registration',
    'page.sla.title': 'SLA Settings',
    'page.sla.breadcrumb': 'Shila Dashboard / Settings / SLA',
    'page.eventlog.title': 'Event Log',
    'page.eventlog.breadcrumb': 'Shila Dashboard / Event Log',
    'create.title': 'Create New Order',
    'create.desc': 'Fill in the details below to create a new L/C order.',
    'create.form.type': 'Transaction Type',
    'create.form.urn': 'URN (manual input)',
    'create.form.subject': 'Subject',
    'create.form.assigned': 'Assigned To',
    'create.form.assigned_loading': 'Loading assignees...',
    'create.form.submit': '➕ Create Order',
    'assignee.title': 'L/C Assignee Master',
    'assignee.desc': 'Add and manage assignees available for new L/C orders.',
    'assignee.form.name': 'Assignee Name',
    'assignee.form.placeholder': 'Enter assignee name',
    'assignee.form.submit': '➕ Add Assignee',
    'assignee.list_title': 'Assignee List',
    'assignee.col_name': 'Name',
    'assignee.empty': 'No assignee available.',
    'assignee.required': 'Assignee is required.',
    'officer_registration.title': 'Officer Registration',
    'officer_registration.desc': 'Add and manage officers responsible for release approval.',
    'officer_registration.form.name': 'Officer Name',
    'officer_registration.form.placeholder': 'Enter officer name',
    'officer_registration.form.submit': '➕ Add Officer',
    'officer_registration.list_title': 'Officer List',
    'officer_registration.col_name': 'Name',
    'officer_registration.empty': 'No officer available.',
    'officer_registration.required': 'Officer is required.',
    'kpi.active': 'Active L/Cs',
    'kpi.completed': 'Completed Today',
    'kpi.breaches': 'SLA Breaches',
    'kpi.avgtime': 'Avg Processing Time',
    'chart.title': 'Average Stage Duration',
    'chart.inbox': 'Inbox Wait',
    'chart.drafting': 'Drafting',
    'chart.checking': 'Checking',
    'chart.total': 'Total Lifecycle',
    'recent.title': 'Recent Activity',
    'recent.col_time': 'Time',
    'recent.col_event': 'Event',
    'recent.empty': 'No activity yet. Process an L/C from the Queue.',
    'summary.title': "Today's L/C Summary",
    'summary.col_urn': 'URN',
    'summary.col_type': 'Type',
    'summary.col_subject': 'Subject',
    'summary.col_assigned': 'Analyst',
    'summary.col_released_by': 'Releaser Officer',
    'summary.col_status': 'Status',
    'summary.col_received': 'Received',
    'summary.col_elapsed': 'Elapsed',
    'summary.col_sla': 'SLA',
    'exec.import_processed': 'Import Processed',
    'exec.export_processed': 'Export Processed',
    'exec.bg_processed': 'Bank Guarantee Processed',
    'exec.import_sla': 'Import SLA %',
    'exec.export_sla': 'Export SLA %',
    'exec.bg_sla': 'Bank Guarantee SLA %',
    'exec.total_breaches': 'Total Breaches',
    'exec.avg_time': 'Avg Cycle Time',
    'exec.comparison_title': 'Import vs Export vs BG: Stage Duration',
    'exec.bottleneck_title': 'Bottleneck Focus',
    'exec.bottleneck_empty': 'No stage data yet',
    'exec.import_label': 'Import',
    'exec.export_label': 'Export',
    'exec.bg_label': 'Bank Guarantee',
    'exec.ai_title': '🤖 AI Performance Summary',
    'exec.ai_generating': 'Generating AI summary...',
    'exec.ai_refresh': '↻ Refresh',
    'exec.combined_activity': 'Combined Recent Activity',
    'type.import': 'Import',
    'type.export': 'Export',
    'type.bg': 'Bank Guarantee',
    'queue.title': 'L/C Processing Queue',
    'queue.search': 'Search URN or sender…',
    'queue.filter_all': 'All',
    'queue.filter_exception': 'Exception',
    'queue.col_num': '#',
    'queue.col_urn': 'URN',
    'queue.col_subject': 'Subject',
    'queue.col_assigned': 'Assigned To',
    'queue.col_status': 'Status',
    'queue.col_received': 'Received',
    'queue.col_elapsed': 'Elapsed',
    'queue.col_sla': 'SLA',
    'queue.col_action': 'Action',
    'queue.showing': 'Showing',
    'queue.of': 'of',
    'queue.records': 'records',
    'queue.no_records': 'No records found.',
    'officer_release.title': 'Officer Release L/C',
    'officer_release.search': 'Search releasable L/C...',
    'officer_release.col_num': '#',
    'officer_release.col_urn': 'URN',
    'officer_release.col_type': 'Type',
    'officer_release.col_assigned': 'Assigned To',
    'officer_release.col_status': 'Status',
    'officer_release.col_elapsed': 'Elapsed',
    'officer_release.col_action': 'Action',
    'officer_release.no_records': 'No releasable L/C found.',
    'officer_release.select_officer': 'Select officer',
    'action.start_drafting': '▶ Start Drafting',
    'action.start_checking': '🔍 Start Checking',
    'action.release': '✅ Release',
    'action.completed': 'Completed',
    'action.resume': '▶ Resume',
    'action.mark_exception': '⏸ Exception',
    'action.resolve_exception': '▶ Resolve Exception',
    'timeline.received': 'Received',
    'timeline.drafting': 'Drafting',
    'timeline.checking': 'Checking Underlying',
    'timeline.exception': 'Exception',
    'timeline.released': 'Released',
    'timeline.stage_duration': 'Stage Duration Breakdown',
    'timeline.longest_stage': 'Longest Stage',
    'timeline.no_stage_duration': 'Not enough timeline data yet.',
    'timeline.live': 'Live (ongoing)',
    'timeline.desc.received': 'L/C Application received in the system.',
    'timeline.desc.drafting': 'Started drafting the documentary credit',
    'timeline.desc.checking': 'Checking documents and trade compliance.',
    'timeline.desc.exception_active': 'Currently paused due to an exception.',
    'timeline.desc.exception_resolved': 'Exception was resolved.',
    'timeline.exception_resolved_label': 'Resolved',
    'timeline.exception_duration': 'Total Duration',
    'timeline.exception_start': 'Start',
    'timeline.exception_end': 'End',
    'timeline.desc.released': 'L/C has been released via SWIFT.',
    'sla.config_title': '⏱️ SLA Configuration',
    'sla.config_desc': 'Define the maximum Service Level Agreement threshold for L/C processing. Items exceeding the threshold will be flagged as breaches.',
    'sla.max_label': 'SLA Maximum (minutes)',
    'sla.import_max_label': 'Import SLA Maximum (minutes)',
    'sla.export_max_label': 'Export SLA Maximum (minutes)',
    'sla.bg_max_label': 'Bank Guarantee SLA Maximum (minutes)',
    'sla.save': '💾 Save Settings',
    'sla.reset_default': 'Reset to Default',
    'sla.data_title': '🗑️ Data Management',
    'sla.data_desc': 'Reset all L/C data, event logs, and SLA configuration back to defaults. This will regenerate 30 fresh mock records.',
    'sla.reset_all': 'Reset All Data',
    'eventlog.title': 'Event Log',
    'eventlog.clear': 'Clear Log',
    'eventlog.col_timestamp': 'Timestamp',
    'eventlog.col_urn': 'URN',
    'eventlog.col_user': 'User',
    'eventlog.col_action': 'Action',
    'eventlog.col_from': 'From',
    'eventlog.col_to': 'To',
    'eventlog.col_notes': 'Notes',
    'eventlog.empty': 'No events logged yet.',
    'eventlog.events': 'events',
    'sla.ok': 'OK',
    'sla.warning': 'Warning',
    'sla.breach': 'Breach',
    'sla.breached_exception': 'Breached (excl. exception)',
    'toast.sla_saved': 'SLA settings saved successfully!',
    'toast.sla_reset': 'SLA reset to default (120 min).',
    'toast.data_reset': 'All data has been regenerated.',
    'toast.log_cleared': 'Event log cleared.',
    'toast.confirm_reset': 'This will reset ALL data (30 new records, clear event log, reset SLA). Continue?',
    'toast.order_created': 'New order created successfully.',
    'toast.assignee_added': 'Assignee added successfully.',
    'toast.assignee_add_failed': 'Failed to add assignee.',
    'toast.officer_added': 'Officer added successfully.',
    'toast.officer_add_failed': 'Failed to add officer.',
    'note.start_drafting': 'Officer started drafting the L/C.',
    'note.start_checking': 'Draft complete, moved to checking.',
    'note.release': 'L/C released successfully.',
    'note.mark_exception': 'Marked as Exception (SLA paused)',
    'note.resolve_exception': 'Exception resolved. Process resumed.',
    'prompt.mark_exception': 'Enter the reason for exception (e.g., contacting customer, stuck at financing):',
    'prompt.resolve_exception': 'Enter total minutes spent in this exception (Auto-calculated: {0}m):',
    'page.all_lcs.title': 'All L/C Records',
    'create.form.received_at': 'Received Date & Time',
    'create.form.received_at_invalid': 'Invalid Date/Time',
    'date.apply': 'Apply',
    'date.server_time': 'Server Time',
    'date.to': 'to',
    'date.custom': 'Custom Range',
    'date.last_14_days': 'Last 14 Days',
    'date.last_7_days': 'Last 7 Days',
    'date.last_month': 'Last Month',
    'date.today': 'Today',
    'date.yesterday': 'Yesterday',
    'exec.insight_cross_delta': 'Process Delta',
    'exec.insight_export_top': 'Export Bottleneck',
    'exec.insight_gap_next': 'Gap to next:',
    'exec.insight_import_top': 'Import Bottleneck',
    'exec.insight_bg_top': 'BG Bottleneck',
    'exec.sla_compare_current': 'Current Period',
    'exec.sla_compare_loading': 'Comparing data...',
    'exec.sla_compare_previous': 'Previous Period',
    'exec.sla_compare_selector': 'Compare Metric',
    'exec.sla_compare_server_note': 'Based on server timestamp',
    'exec.sla_compare_title': 'SLA Trend Analysis',
    'exec.sla_compare_overall': 'Overall Performance',
    'exec.sla_compare_import': 'Import Operation',
    'exec.sla_compare_export': 'Export Operation',
    'exec.sla_compare_bg': 'Bank Guarantee Operation',
    'exec.sla_compare_trend_up': 'Improved',
    'exec.sla_compare_trend_down': 'Declined',
    'exec.sla_compare_trend_flat': 'Unchanged',
    'queue.col_released_by': 'Released By',
    'queue.col_start_date': 'Start Date',
    'queue.col_time_left_sla': 'Time to SLA',
    'queue.time_breached_by': 'Breached by',
    'queue.time_left': 'left',
    'timeline.stage_share': 'Stage Share',
    'notif.title': 'Notifications',
    'notif.mark_all_read': 'Mark all as read',
    'notif.empty': 'You have no new notifications.',
    'notif.warning_title': 'SLA Early Warning',
    'notif.warning_desc': 'L/C is approaching SLA breach.',
    'notif.warning_desc_params': 'L/C {0} is at {1}m (Threshold: {2}m)',
    'notif.new_lc_title': 'New L/C Received',
    'notif.new_lc_desc': 'A new L/C has been created.',
    'notif.new_lc_desc_params': 'New Application {0} received.',
    'notif.system_title': 'System Notice',
    'notif.system_cutoff_desc': 'System cut-off is at 15:00. Please complete all pending releases.',
    'exec.staff_performance_title': 'Staff & Officer Performance',
    'exec.col_name': 'Name',
    'exec.col_role': 'Role',
    'exec.col_volume': 'Volume',
    'exec.col_breaches': 'Breaches',
    'exec.col_compliance': 'SLA %',
    'exec.col_avg_time': 'Avg Time',
    'lang.label': '🇬🇧 EN',
  },
  id: {
    'nav.main_menu': 'Menu Utama',
    'timeline.export.received': 'Inbox',
    'timeline.export.drafting': 'Pemeriksaan Analis',
    'timeline.export.checking': 'Pemeriksaan Officer',
    'timeline.export.released': 'Rilis',
    'chart.export.inbox': 'Inbox',
    'chart.export.drafting': 'Pemeriksaan Analis',
    'chart.export.checking': 'Pemeriksaan Officer',
    'action.export.start_drafting': '▶ Mulai Pemeriksaan Analis',
    'action.export.start_checking': '🔍 Mulai Pemeriksaan Officer',
    'timeline.bank guarantee.received': 'Inbox',
    'timeline.bank guarantee.drafting': 'Proses',
    'timeline.bank guarantee.checking': 'Pemeriksaan',
    'timeline.bank guarantee.released': 'Rilis',
    'chart.bank guarantee.inbox': 'Inbox',
    'chart.bank guarantee.drafting': 'Proses',
    'chart.bank guarantee.checking': 'Pemeriksaan',
    'action.bank guarantee.start_drafting': '▶ Mulai Proses',
    'action.bank guarantee.start_checking': '🔍 Mulai Pemeriksaan',
    'timeline.import.received': 'Inbox',
    'timeline.import.drafting': 'Penyusunan',
    'timeline.import.checking': 'Pemeriksaan',
    'timeline.import.released': 'Rilis',
    'chart.import.inbox': 'Tunggu Kotak Masuk',
    'chart.import.drafting': 'Penyusunan',
    'chart.import.checking': 'Pemeriksaan',
    'action.import.start_drafting': '▶ Mulai Menyusun',
    'action.import.start_checking': '🔍 Mulai Memeriksa',
    'nav.operations': 'Operasional',
    'nav.exec_dashboard': 'Dasbor Eksekutif',
    'nav.import': 'Impor',
    'nav.export': 'Ekspor',
    'nav.bg': 'Bank Garansi',
    'nav.dashboard': 'Dasbor',
    'nav.queue': 'Antrian L/C',
    'nav.officer_release': 'Rilis L/C Officer',
    'nav.create': 'Buat Pesanan',
    'nav.master_data': 'Data Master',
    'nav.assignee_master': 'Master Penugasan L/C',
    'nav.officer_registration': 'Registrasi Officer',
    'nav.sla': 'Pengaturan SLA',
    'nav.eventlog': 'Log Aktivitas',
    'sidebar.user_role': 'Administrator',
    'topbar.reset': '↻ Reset Data',
    'page.exec_dashboard.title': 'Dasbor Eksekutif',
    'page.exec_dashboard.breadcrumb': 'Shila Dashboard / Ringkasan Eksekutif',
    'page.import.title': 'Operasi Impor',
    'page.import.breadcrumb': 'Shila Dashboard / Impor',
    'page.export.title': 'Operasi Ekspor',
    'page.export.breadcrumb': 'Shila Dashboard / Ekspor',
    'page.bg.title': 'Operasi Bank Garansi',
    'page.bg.breadcrumb': 'Shila Dashboard / Bank Garansi',
    'page.dashboard.title': 'Dasbor',
    'page.dashboard.breadcrumb': 'Shila Dashboard / Ringkasan',
    'page.queue.title': 'Antrian Proses L/C',
    'page.queue.breadcrumb': 'Shila Dashboard / Antrian L/C',
    'page.officer_release.title': 'Rilis L/C Officer',
    'page.officer_release.breadcrumb': 'Shila Dashboard / Rilis Officer',
    'page.create.title': 'Buat Pesanan',
    'page.create.breadcrumb': 'Shila Dashboard / Buat Pesanan',
    'page.assignee_master.title': 'Master Penugasan L/C',
    'page.assignee_master.breadcrumb': 'Shila Dashboard / Data Master / Penugasan',
    'page.officer_registration.title': 'Registrasi Officer',
    'page.officer_registration.breadcrumb': 'Shila Dashboard / Data Master / Registrasi Officer',
    'page.sla.title': 'Pengaturan SLA',
    'page.sla.breadcrumb': 'Shila Dashboard / Pengaturan / SLA',
    'page.eventlog.title': 'Log Aktivitas',
    'page.eventlog.breadcrumb': 'Shila Dashboard / Log Aktivitas',
    'create.title': 'Buat Pesanan Baru',
    'create.desc': 'Isi detail di bawah ini untuk membuat pesanan L/C baru.',
    'create.form.type': 'Tipe Transaksi',
    'create.form.urn': 'URN (input manual)',
    'create.form.subject': 'Subjek',
    'create.form.assigned': 'Ditugaskan Kepada',
    'create.form.assigned_loading': 'Memuat penugasan...',
    'create.form.submit': '➕ Buat Pesanan',
    'assignee.title': 'Master Penugasan L/C',
    'assignee.desc': 'Tambah dan kelola penugasan yang tersedia untuk pesanan L/C baru.',
    'assignee.form.name': 'Nama Penugasan',
    'assignee.form.placeholder': 'Masukkan nama penugasan',
    'assignee.form.submit': '➕ Tambah Penugasan',
    'assignee.list_title': 'Daftar Penugasan',
    'assignee.col_name': 'Nama',
    'assignee.empty': 'Tidak ada penugasan yang tersedia.',
    'assignee.required': 'Penugasan wajib diisi.',
    'officer_registration.title': 'Registrasi Officer',
    'officer_registration.desc': 'Tambah dan kelola officer yang bertanggung jawab untuk persetujuan rilis.',
    'officer_registration.form.name': 'Nama Officer',
    'officer_registration.form.placeholder': 'Masukkan nama officer',
    'officer_registration.form.submit': '➕ Tambah Officer',
    'officer_registration.list_title': 'Daftar Officer',
    'officer_registration.col_name': 'Nama',
    'officer_registration.empty': 'Tidak ada officer yang tersedia.',
    'officer_registration.required': 'Officer wajib diisi.',
    'kpi.active': 'L/C Aktif',
    'kpi.completed': 'Selesai Hari Ini',
    'kpi.breaches': 'Pelanggaran SLA',
    'kpi.avgtime': 'Waktu Proses Rata-rata',
    'chart.title': 'Durasi Rata-rata Tahap',
    'chart.inbox': 'Tunggu Kotak Masuk',
    'chart.drafting': 'Penyusunan',
    'chart.checking': 'Pemeriksaan',
    'chart.total': 'Total Siklus Hidup',
    'recent.title': 'Aktivitas Terbaru',
    'recent.col_time': 'Waktu',
    'recent.col_event': 'Aktivitas',
    'recent.empty': 'Belum ada aktivitas. Proses L/C dari Antrian.',
    'summary.title': 'Ringkasan L/C Hari Ini',
    'summary.col_urn': 'URN',
    'summary.col_type': 'Tipe',
    'summary.col_subject': 'Subjek',
    'summary.col_assigned': 'Analis',
    'summary.col_released_by': 'Officer Rilis',
    'summary.col_status': 'Status',
    'summary.col_received': 'Diterima',
    'summary.col_elapsed': 'Berlalu',
    'summary.col_sla': 'SLA',
    'exec.import_processed': 'Impor Diproses',
    'exec.export_processed': 'Ekspor Diproses',
    'exec.bg_processed': 'Bank Garansi Diproses',
    'exec.import_sla': '% SLA Impor',
    'exec.export_sla': '% SLA Ekspor',
    'exec.bg_sla': '% SLA Bank Garansi',
    'exec.total_breaches': 'Total Pelanggaran',
    'exec.avg_time': 'Waktu Siklus Rata-rata',
    'exec.comparison_title': 'Impor vs Ekspor vs BG: Durasi Tahap',
    'exec.bottleneck_title': 'Fokus Bottleneck',
    'exec.bottleneck_empty': 'Belum ada data tahap',
    'exec.import_label': 'Impor',
    'exec.export_label': 'Ekspor',
    'exec.bg_label': 'Bank Garansi',
    'exec.ai_title': '🤖 Ringkasan Kinerja AI',
    'exec.ai_generating': 'Menghasilkan ringkasan AI...',
    'exec.ai_refresh': '↻ Segarkan',
    'exec.combined_activity': 'Aktivitas Terbaru Gabungan',
    'type.import': 'Impor',
    'type.export': 'Ekspor',
    'type.bg': 'Bank Garansi',
    'queue.title': 'Antrian Proses L/C',
    'queue.search': 'Cari URN atau pengirim…',
    'queue.filter_all': 'Semua',
    'queue.filter_exception': 'Pengecualian',
    'queue.col_num': '#',
    'queue.col_urn': 'URN',
    'queue.col_subject': 'Subjek',
    'queue.col_assigned': 'Ditugaskan Kepada',
    'queue.col_status': 'Status',
    'queue.col_received': 'Diterima',
    'queue.col_elapsed': 'Berlalu',
    'queue.col_sla': 'SLA',
    'queue.col_action': 'Aksi',
    'queue.showing': 'Menampilkan',
    'queue.of': 'dari',
    'queue.records': 'data',
    'queue.no_records': 'Data tidak ditemukan.',
    'officer_release.title': 'Rilis L/C Officer',
    'officer_release.search': 'Cari L/C siap rilis...',
    'officer_release.col_num': '#',
    'officer_release.col_urn': 'URN',
    'officer_release.col_type': 'Tipe',
    'officer_release.col_assigned': 'Ditugaskan Kepada',
    'officer_release.col_status': 'Status',
    'officer_release.col_elapsed': 'Berlalu',
    'officer_release.col_action': 'Aksi',
    'officer_release.no_records': 'Tidak ada L/C siap rilis ditemukan.',
    'officer_release.select_officer': 'Pilih officer',
    'action.start_drafting': '▶ Mulai Menyusun',
    'action.start_checking': '🔍 Mulai Memeriksa',
    'action.release': '✅ Rilis',
    'action.completed': 'Selesai',
    'action.resume': '▶ Lanjutkan',
    'action.mark_exception': '⏸ Pengecualian',
    'action.resolve_exception': '▶ Selesaikan Pengecualian',
    'timeline.received': 'Diterima',
    'timeline.drafting': 'Menyusun',
    'timeline.checking': 'Memeriksa Dokumen',
    'timeline.exception': 'Pengecualian',
    'timeline.released': 'Dirilis',
    'timeline.stage_duration': 'Rincian Durasi Tahap',
    'timeline.longest_stage': 'Tahap Terlama',
    'timeline.no_stage_duration': 'Data timeline belum cukup.',
    'timeline.live': 'Live (berlangsung)',
    'timeline.desc.received': 'Aplikasi L/C diterima di sistem.',
    'timeline.desc.drafting': 'Mulai menyusun kredit dokumenter',
    'timeline.desc.checking': 'Memeriksa dokumen dan kepatuhan perdagangan.',
    'timeline.desc.exception_active': 'Saat ini dijeda karena ada pengecualian.',
    'timeline.desc.exception_resolved': 'Pengecualian telah diselesaikan.',
    'timeline.exception_resolved_label': 'Terselesaikan',
    'timeline.exception_duration': 'Total Durasi',
    'timeline.exception_start': 'Mulai',
    'timeline.exception_end': 'Selesai',
    'timeline.desc.released': 'L/C telah dirilis melalui SWIFT.',
    'sla.config_title': '⏱️ Konfigurasi SLA',
    'sla.config_desc': 'Tentukan ambang batas maksimum Service Level Agreement untuk pemrosesan L/C. L/C yang melampaui ambang batas akan ditandai sebagai pelanggaran.',
    'sla.max_label': 'SLA Maksimum (menit)',
    'sla.import_max_label': 'Maksimum SLA Impor (menit)',
    'sla.export_max_label': 'Maksimum SLA Ekspor (menit)',
    'sla.bg_max_label': 'Maksimum SLA Bank Garansi (menit)',
    'sla.save': '💾 Simpan Pengaturan',
    'sla.reset_default': 'Kembalikan ke Default',
    'sla.data_title': '🗑️ Manajemen Data',
    'sla.data_desc': 'Reset semua data L/C, log aktivitas, dan konfigurasi SLA kembali ke default. Ini akan mengenerate 30 data mock baru.',
    'sla.reset_all': 'Reset Semua Data',
    'eventlog.title': 'Log Aktivitas',
    'eventlog.clear': 'Bersihkan Log',
    'eventlog.col_timestamp': 'Waktu',
    'eventlog.col_urn': 'URN',
    'eventlog.col_user': 'Pengguna',
    'eventlog.col_action': 'Aksi',
    'eventlog.col_from': 'Dari',
    'eventlog.col_to': 'Ke',
    'eventlog.col_notes': 'Catatan',
    'eventlog.empty': 'Belum ada aktivitas dicatat.',
    'eventlog.events': 'aktivitas',
    'sla.ok': 'OK',
    'sla.warning': 'Peringatan',
    'sla.breach': 'Pelanggaran',
    'sla.breached_exception': 'Melebihi SLA (tdk incl. pengecualian)',
    'toast.sla_saved': 'Pengaturan SLA berhasil disimpan!',
    'toast.sla_reset': 'SLA dikembalikan ke default (120 menit).',
    'toast.data_reset': 'Semua data telah di-generate ulang.',
    'toast.log_cleared': 'Log aktivitas dibersihkan.',
    'toast.confirm_reset': 'Tindakan ini akan mereset SEMUA data (30 data baru, bersihkan log, reset SLA). Lanjutkan?',
    'toast.order_created': 'Pesanan baru berhasil dibuat.',
    'toast.assignee_added': 'Penugasan berhasil ditambahkan.',
    'toast.assignee_add_failed': 'Gagal menambahkan penugasan.',
    'toast.officer_added': 'Officer berhasil ditambahkan.',
    'toast.officer_add_failed': 'Gagal menambahkan officer.',
    'note.start_drafting': 'Officer mulai menyusun L/C.',
    'note.start_checking': 'Penyusunan selesai, pindah ke pemeriksaan.',
    'note.release': 'L/C berhasil dirilis.',
    'note.mark_exception': 'Ditandai sebagai Pengecualian (SLA dijeda)',
    'note.resolve_exception': 'Pengecualian diselesaikan. Proses dilanjutkan.',
    'prompt.mark_exception': 'Masukkan alasan pengecualian (contoh: hubungi pelanggan, tertunda di pembiayaan):',
    'prompt.resolve_exception': 'Masukkan total waktu pengecualian (Dihitung otomatis: {0}m):',
    'page.all_lcs.title': 'Semua Data L/C',
    'create.form.received_at': 'Tanggal & Waktu Diterima',
    'create.form.received_at_invalid': 'Tanggal/Waktu Tidak Valid',
    'date.apply': 'Terapkan',
    'date.server_time': 'Waktu Server',
    'date.to': 'hingga',
    'date.custom': 'Rentang Kustom',
    'date.last_14_days': '14 Hari Terakhir',
    'date.last_7_days': '7 Hari Terakhir',
    'date.last_month': 'Bulan Lalu',
    'date.today': 'Hari Ini',
    'date.yesterday': 'Kemarin',
    'exec.insight_cross_delta': 'Selisih Proses',
    'exec.insight_export_top': 'Bottleneck Ekspor',
    'exec.insight_gap_next': 'Selisih ke berikutnya:',
    'exec.insight_import_top': 'Bottleneck Impor',
    'exec.insight_bg_top': 'Bottleneck BG',
    'exec.sla_compare_current': 'Periode Saat Ini',
    'exec.sla_compare_loading': 'Membandingkan data...',
    'exec.sla_compare_previous': 'Periode Sebelumnya',
    'exec.sla_compare_selector': 'Metrik Perbandingan',
    'exec.sla_compare_server_note': 'Berdasarkan waktu server',
    'exec.sla_compare_title': 'Analisis Tren SLA',
    'exec.sla_compare_overall': 'Kinerja Keseluruhan',
    'exec.sla_compare_import': 'Operasi Impor',
    'exec.sla_compare_export': 'Operasi Ekspor',
    'exec.sla_compare_bg': 'Operasi Bank Garansi',
    'exec.sla_compare_trend_up': 'Meningkat',
    'exec.sla_compare_trend_down': 'Menurun',
    'exec.sla_compare_trend_flat': 'Tidak Berubah',
    'queue.col_released_by': 'Dirilis Oleh',
    'queue.col_start_date': 'Tanggal Mulai',
    'queue.col_time_left_sla': 'Waktu ke SLA',
    'queue.time_breached_by': 'Lewat',
    'queue.time_left': 'tersisa',
    'timeline.stage_share': 'Porsi Tahapan',
    'notif.title': 'Notifikasi',
    'notif.mark_all_read': 'Tandai semua dibaca',
    'notif.empty': 'Tidak ada notifikasi baru.',
    'notif.warning_title': 'Peringatan Dini SLA',
    'notif.warning_desc': 'L/C mendekati batas SLA.',
    'notif.warning_desc_params': 'L/C {0} mencapai {1}m (Batas: {2}m)',
    'notif.new_lc_title': 'L/C Baru Diterima',
    'notif.new_lc_desc': 'Aplikasi L/C baru telah dibuat.',
    'notif.new_lc_desc_params': 'Aplikasi baru {0} diterima.',
    'notif.system_title': 'Pemberitahuan Sistem',
    'notif.system_cutoff_desc': 'Waktu cut-off sistem adalah 15:00. Harap selesaikan L/C yang tertunda.',
    'exec.staff_performance_title': 'Kinerja Staf & Pejabat',
    'exec.col_name': 'Nama',
    'exec.col_role': 'Peran',
    'exec.col_volume': 'Volume',
    'exec.col_breaches': 'Pelanggaran',
    'exec.col_compliance': 'SLA %',
    'exec.col_avg_time': 'Rata-rata',
    'lang.label': '🇮🇩 ID',
  },
};

export function getLang(): string {
  return localStorage.getItem(LANG_KEY) || 'en';
}

export function setLang(lang: string): void {
  localStorage.setItem(LANG_KEY, lang);
}

export function t(key: string): string {
  const lang = getLang();
  return (translations[lang] && translations[lang][key]) || translations.en[key] || key;
}

export function toggleLang(onChange?: () => void): void {
  const current = getLang();
  const next = current === 'en' ? 'id' : 'en';
  setLang(next);
  applyStaticTranslations();
  updateLangButton();
  if (onChange) {
    onChange();
  }
}

export function updateLangButton(): void {
  const btn = document.getElementById('lang-toggle');
  if (btn) {
    btn.textContent = t('lang.label');
  }
}

export function applyStaticTranslations(): void {
  document.querySelectorAll('[data-i18n]').forEach((el) => {
    const key = el.getAttribute('data-i18n') || '';
    const val = t(key);
    if (el instanceof HTMLInputElement && el.type !== 'number') {
      el.placeholder = val;
    } else {
      el.textContent = val;
    }
  });
}
