const LANG_KEY = 'shila_lang';

const translations: any = {
  en: {
    'nav.main_menu': 'Main Menu',
    'nav.operations': 'Operations',
    'nav.exec_dashboard': 'Executive Dashboard',
    'nav.import': 'Import',
    'nav.export': 'Export',
    'nav.dashboard': 'Dashboard',
    'nav.queue': 'L/C Queue',
    'nav.officer_release': 'Officer Release L/C',
    'nav.create': 'Create Order',
    'nav.master_data': 'Master Data',
    'nav.assignee_master': 'L/C Assignee Master',
    'nav.officer_registration': 'Officer Registration',
    'nav.sla': 'SLA Settings',
    'nav.eventlog': 'Event Log',
    'sidebar.user_role': 'Administrator',
    'topbar.reset': '↻ Reset Data',
    'page.exec_dashboard.title': 'Executive Dashboard',
    'page.exec_dashboard.breadcrumb': 'Shila Dashboard / Executive Overview',
    'page.import.title': 'Import Operations',
    'page.import.breadcrumb': 'Shila Dashboard / Import',
    'page.export.title': 'Export Operations',
    'page.export.breadcrumb': 'Shila Dashboard / Export',
    'page.dashboard.title': 'Dashboard',
    'page.dashboard.breadcrumb': 'Shila Dashboard / Overview',
    'page.queue.title': 'L/C Processing Queue',
    'page.queue.breadcrumb': 'Shila Dashboard / L/C Queue',
    'page.officer_release.title': 'Officer Release L/C',
    'page.officer_release.breadcrumb': 'Shila Dashboard / Officer Release',
    'page.create.title': 'Create Order',
    'page.create.breadcrumb': 'Shila Dashboard / Create Order',
    'page.assignee_master.title': 'L/C Assignee Master',
    'page.assignee_master.breadcrumb': 'Shila Dashboard / Master Data / Assignee',
    'page.officer_registration.title': 'Officer Registration',
    'page.officer_registration.breadcrumb': 'Shila Dashboard / Master Data / Officer Registration',
    'page.sla.title': 'SLA Settings',
    'page.sla.breadcrumb': 'Shila Dashboard / Settings / SLA',
    'page.eventlog.title': 'Event Log',
    'page.eventlog.breadcrumb': 'Shila Dashboard / Event Log',
    'create.title': 'Create New Order',
    'create.desc': 'Fill in the details below to create a new L/C order.',
    'create.form.type': 'Transaction Type',
    'create.form.sender': 'Sender Email',
    'create.form.subject': 'Subject',
    'create.form.assigned': 'Assigned To',
    'create.form.assigned_loading': 'Loading assignees...',
    'create.form.submit': '➕ Create Order',
    'assignee.title': 'L/C Assignee Master',
    'assignee.desc': 'Add and manage assignees available for new L/C orders.',
    'assignee.form.name': 'Assignee Name',
    'assignee.form.placeholder': 'Enter assignee name',
    'assignee.form.submit': '➕ Add Assignee',
    'assignee.list_title': 'Assignee List',
    'assignee.col_name': 'Name',
    'assignee.empty': 'No assignee available.',
    'assignee.required': 'Assignee is required.',
    'officer_registration.title': 'Officer Registration',
    'officer_registration.desc': 'Add and manage officers responsible for release approval.',
    'officer_registration.form.name': 'Officer Name',
    'officer_registration.form.placeholder': 'Enter officer name',
    'officer_registration.form.submit': '➕ Add Officer',
    'officer_registration.list_title': 'Officer List',
    'officer_registration.col_name': 'Name',
    'officer_registration.empty': 'No officer available.',
    'officer_registration.required': 'Officer is required.',
    'kpi.active': 'Active L/Cs',
    'kpi.completed': 'Completed Today',
    'kpi.breaches': 'SLA Breaches',
    'kpi.avgtime': 'Avg Processing Time',
    'chart.title': 'Average Stage Duration',
    'chart.inbox': 'Inbox Wait',
    'chart.drafting': 'Drafting',
    'chart.checking': 'Checking',
    'chart.total': 'Total Lifecycle',
    'recent.title': 'Recent Activity',
    'recent.col_time': 'Time',
    'recent.col_event': 'Event',
    'recent.empty': 'No activity yet. Process an L/C from the Queue.',
    'summary.title': "Today's L/C Summary",
    'summary.col_urn': 'URN',
    'summary.col_type': 'Type',
    'summary.col_sender': 'Sender',
    'summary.col_status': 'Status',
    'summary.col_received': 'Received',
    'summary.col_elapsed': 'Elapsed',
    'summary.col_sla': 'SLA',
    'exec.import_processed': 'Import Processed',
    'exec.export_processed': 'Export Processed',
    'exec.import_sla': 'Import SLA %',
    'exec.export_sla': 'Export SLA %',
    'exec.total_breaches': 'Total Breaches',
    'exec.avg_time': 'Avg Cycle Time',
    'exec.comparison_title': 'Import vs Export: Stage Duration',
    'exec.import_label': 'Import',
    'exec.export_label': 'Export',
    'exec.ai_title': '🤖 AI Performance Summary',
    'exec.ai_generating': 'Generating AI summary...',
    'exec.ai_refresh': '↻ Refresh',
    'exec.combined_activity': 'Combined Recent Activity',
    'type.import': 'Import',
    'type.export': 'Export',
    'queue.title': 'L/C Processing Queue',
    'queue.search': 'Search URN or sender…',
    'queue.filter_all': 'All',
    'queue.filter_exception': 'Exception',
    'queue.col_num': '#',
    'queue.col_urn': 'URN',
    'queue.col_sender': 'Sender',
    'queue.col_subject': 'Subject',
    'queue.col_assigned': 'Assigned To',
    'queue.col_status': 'Status',
    'queue.col_received': 'Received',
    'queue.col_elapsed': 'Elapsed',
    'queue.col_sla': 'SLA',
    'queue.col_action': 'Action',
    'queue.showing': 'Showing',
    'queue.of': 'of',
    'queue.records': 'records',
    'queue.no_records': 'No records found.',
    'officer_release.title': 'Officer Release L/C',
    'officer_release.search': 'Search releasable L/C...',
    'officer_release.col_num': '#',
    'officer_release.col_urn': 'URN',
    'officer_release.col_type': 'Type',
    'officer_release.col_sender': 'Sender',
    'officer_release.col_assigned': 'Assigned To',
    'officer_release.col_status': 'Status',
    'officer_release.col_elapsed': 'Elapsed',
    'officer_release.col_action': 'Action',
    'officer_release.no_records': 'No releasable L/C found.',
    'officer_release.select_officer': 'Select officer',
    'action.start_drafting': '▶ Start Drafting',
    'action.start_checking': '🔍 Start Checking',
    'action.release': '✅ Release',
    'action.completed': 'Completed',
    'action.resume': '▶ Resume',
    'action.mark_exception': '⏸ Exception',
    'action.resolve_exception': '▶ Resolve Exception',
    'timeline.received': 'Received',
    'timeline.drafting': 'Drafting',
    'timeline.checking': 'Checking Underlying',
    'timeline.exception': 'Exception',
    'timeline.released': 'Released',
    'timeline.desc.received': 'L/C Application received in the system.',
    'timeline.desc.drafting': 'Started drafting the documentary credit',
    'timeline.desc.checking': 'Checking documents and trade compliance.',
    'timeline.desc.exception_active': 'Currently paused due to an exception.',
    'timeline.desc.exception_resolved': 'Exception was resolved.',
    'timeline.desc.released': 'L/C has been released via SWIFT.',
    'sla.config_title': '⏱️ SLA Configuration',
    'sla.config_desc': 'Define the minimum and maximum Service Level Agreement thresholds for L/C processing. Items exceeding the maximum will be flagged as breaches.',
    'sla.min_label': 'SLA Minimum (minutes)',
    'sla.max_label': 'SLA Maximum (minutes)',
    'sla.save': '💾 Save Settings',
    'sla.reset_default': 'Reset to Default',
    'sla.data_title': '🗑️ Data Management',
    'sla.data_desc': 'Reset all L/C data, event logs, and SLA configuration back to defaults. This will regenerate 30 fresh mock records.',
    'sla.reset_all': 'Reset All Data',
    'eventlog.title': 'Event Log',
    'eventlog.clear': 'Clear Log',
    'eventlog.col_timestamp': 'Timestamp',
    'eventlog.col_urn': 'URN',
    'eventlog.col_user': 'User',
    'eventlog.col_action': 'Action',
    'eventlog.col_from': 'From',
    'eventlog.col_to': 'To',
    'eventlog.col_notes': 'Notes',
    'eventlog.empty': 'No events logged yet.',
    'eventlog.events': 'events',
    'sla.ok': 'OK',
    'sla.warning': 'Warning',
    'sla.breach': 'Breach',
    'toast.sla_saved': 'SLA settings saved successfully!',
    'toast.sla_reset': 'SLA reset to defaults (90-120 min).',
    'toast.data_reset': 'All data has been regenerated.',
    'toast.log_cleared': 'Event log cleared.',
    'toast.confirm_reset': 'This will reset ALL data (30 new records, clear event log, reset SLA). Continue?',
    'toast.order_created': 'New order created successfully.',
    'toast.assignee_added': 'Assignee added successfully.',
    'toast.assignee_add_failed': 'Failed to add assignee.',
    'toast.officer_added': 'Officer added successfully.',
    'toast.officer_add_failed': 'Failed to add officer.',
    'note.start_drafting': 'Officer started drafting the L/C.',
    'note.start_checking': 'Draft complete, moved to checking.',
    'note.release': 'L/C released successfully.',
    'note.mark_exception': 'Marked as Exception (SLA paused)',
    'note.resolve_exception': 'Exception resolved. Process resumed.',
    'prompt.mark_exception': 'Enter the reason for exception (e.g., contacting customer, stuck at financing):',
    'prompt.resolve_exception': 'Enter total minutes spent in this exception (Auto-calculated: {0}m):',
    'lang.label': '🇬🇧 EN',
  },
  id: {
    'nav.main_menu': 'Menu Utama',
    'nav.operations': 'Operasional',
    'nav.exec_dashboard': 'Dasbor Eksekutif',
    'nav.import': 'Impor',
    'nav.export': 'Ekspor',
    'nav.dashboard': 'Dasbor',
    'nav.queue': 'Antrian L/C',
    'nav.officer_release': 'Rilis L/C Officer',
    'nav.create': 'Buat Pesanan',
    'nav.master_data': 'Data Master',
    'nav.assignee_master': 'Master Penugasan L/C',
    'nav.officer_registration': 'Registrasi Officer',
    'nav.sla': 'Pengaturan SLA',
    'nav.eventlog': 'Log Aktivitas',
    'sidebar.user_role': 'Administrator',
    'topbar.reset': '↻ Reset Data',
    'page.exec_dashboard.title': 'Dasbor Eksekutif',
    'page.exec_dashboard.breadcrumb': 'Shila Dashboard / Ringkasan Eksekutif',
    'page.import.title': 'Operasi Impor',
    'page.import.breadcrumb': 'Shila Dashboard / Impor',
    'page.export.title': 'Operasi Ekspor',
    'page.export.breadcrumb': 'Shila Dashboard / Ekspor',
    'page.dashboard.title': 'Dasbor',
    'page.dashboard.breadcrumb': 'Shila Dashboard / Ringkasan',
    'page.queue.title': 'Antrian Proses L/C',
    'page.queue.breadcrumb': 'Shila Dashboard / Antrian L/C',
    'page.officer_release.title': 'Rilis L/C Officer',
    'page.officer_release.breadcrumb': 'Shila Dashboard / Rilis Officer',
    'page.create.title': 'Buat Pesanan',
    'page.create.breadcrumb': 'Shila Dashboard / Buat Pesanan',
    'page.assignee_master.title': 'Master Penugasan L/C',
    'page.assignee_master.breadcrumb': 'Shila Dashboard / Data Master / Penugasan',
    'page.officer_registration.title': 'Registrasi Officer',
    'page.officer_registration.breadcrumb': 'Shila Dashboard / Data Master / Registrasi Officer',
    'page.sla.title': 'Pengaturan SLA',
    'page.sla.breadcrumb': 'Shila Dashboard / Pengaturan / SLA',
    'page.eventlog.title': 'Log Aktivitas',
    'page.eventlog.breadcrumb': 'Shila Dashboard / Log Aktivitas',
    'lang.label': '🇮🇩 ID',
  },
};

export function getLang(): string {
  return localStorage.getItem(LANG_KEY) || 'en';
}

export function setLang(lang: string): void {
  localStorage.setItem(LANG_KEY, lang);
}

export function t(key: string): string {
  const lang = getLang();
  return (translations[lang] && translations[lang][key]) || translations.en[key] || key;
}

export function toggleLang(onChange?: () => void): void {
  const current = getLang();
  const next = current === 'en' ? 'id' : 'en';
  setLang(next);
  applyStaticTranslations();
  updateLangButton();
  if (onChange) {
    onChange();
  }
}

export function updateLangButton(): void {
  const btn = document.getElementById('lang-toggle');
  if (btn) {
    btn.textContent = t('lang.label');
  }
}

export function applyStaticTranslations(): void {
  document.querySelectorAll('[data-i18n]').forEach((el) => {
    const key = el.getAttribute('data-i18n') || '';
    const val = t(key);
    if (el instanceof HTMLInputElement && el.type !== 'number') {
      el.placeholder = val;
    } else {
      el.textContent = val;
    }
  });
}
