@echo off
echo Starting Trade Import Dashboard...

echo Starting Backend server...
start "Backend" cmd /k "cd backend && go run cmd/server/main.go"

echo Starting Frontend server...
start "Frontend" cmd /k "cd frontend && npm start"
